/**
 * Generates supabase/seed.sql from the fictional data in data/*.ts.
 *
 *   npm run db:seed:generate
 *
 * IDs are deterministic (md5 of a stable key), so the seed is idempotent and
 * readable: `md5('person:marek')::uuid`.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { people } from "../data/people";
import { relationships } from "../data/relationships";
import { events } from "../data/events";
import { lore } from "../data/lore";
import type { Place } from "../types/domain";

const q = (v: string | null | undefined) => (v === null || v === undefined ? "null" : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null | undefined) => (v === null || v === undefined ? "null" : String(v));
const arr = (v: string[] | undefined) => (v && v.length ? `array[${v.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const id = (kind: string, key: string) => `md5(${q(`${kind}:${key}`)})::uuid`;

/** Demo: a few rows stay drafts so preview/publish can be tried right away. */
const DRAFT_LORE = new Set(["l-rafal-zajecie"]);
const DRAFT_EVENTS = new Set(["e-rowery"]);

const lines: string[] = [];
const out = (s = "") => lines.push(s);

out("-- Generated by scripts/generate-seed.ts — do not edit by hand.");
out("-- Fictional sample data: 20 people, ~45 relationships, events and lore.");
out("begin;");
out("set local app.skip_audit = 'on';");
out();

// Locations (deduplicated by name).
const locations = new Map<string, Place>();
for (const item of [...relationships, ...events]) if (item.location) locations.set(item.location.name, item.location);
out("insert into public.locations (id, name, lat, lng) values");
out(
  [...locations.values()]
    .map((l) => `  (${id("location", l.name)}, ${q(l.name)}, ${l.lat}, ${l.lng})`)
    .join(",\n") + "\non conflict (id) do nothing;",
);
out();

out("insert into public.people (id, slug, first_name, last_name, nickname, aliases, bio, legend, category, tags, first_seen, status) values");
out(
  people
    .map(
      (p) =>
        `  (${id("person", p.id)}, ${q(p.id)}, ${q(p.name)}, ${q(p.lastName)}, ${q(p.nickname)}, ${arr(p.aliases)}, ${q(p.bio)}, ${q(p.legend)}, ${q(p.category)}, ${arr(p.tags ?? ["Czechowice"])}, ${n(p.firstSeen)}, 'published')`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
);
out();

out("insert into public.relationships (id, slug, person_a, person_b, type, strength, since_year, until_year, description, tone, confidence, source_type, location_id, status) values");
out(
  relationships
    .map(
      (r) =>
        `  (${id("relationship", r.id)}, ${q(r.id)}, ${id("person", r.personA)}, ${id("person", r.personB)}, ${q(r.type)}, ${Math.round(r.strength * 100)}, ${n(r.since)}, ${n(r.until)}, ${q(r.description)}, ${q(r.tone)}, ${q(r.confidence ?? "confirmed")}, 'personal', ${r.location ? id("location", r.location.name) : "null"}, 'published')`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
);
out();

out("insert into public.events (id, title, description, year, month, location_id, confidence, source_type, status) values");
out(
  events
    .map(
      (e) =>
        `  (${id("event", e.id)}, ${q(e.title)}, ${q(e.description)}, ${n(e.year)}, ${n(e.month)}, ${e.location ? id("location", e.location.name) : "null"}, ${q(e.confidence ?? "confirmed")}, 'personal', ${DRAFT_EVENTS.has(e.id) ? "'draft'" : "'published'"})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
);
out();

out("insert into public.event_people (event_id, person_id) values");
out(
  events
    .flatMap((e) => e.people.map((p) => `  (${id("event", e.id)}, ${id("person", p)})`))
    .join(",\n") + "\non conflict do nothing;",
);
out();

const eventRels = events.flatMap((e) => (e.relationshipIds ?? []).map((r) => `  (${id("event", e.id)}, ${id("relationship", r)})`));
out("insert into public.event_relationships (event_id, relationship_id) values");
out(eventRels.join(",\n") + "\non conflict do nothing;");
out();

// Lore: standalone entries + per-person fun facts.
const loreRows: { key: string; title?: string; content: string; type: string; year?: number; confidence: string; people: string[] }[] = [
  ...lore.map((l) => ({ key: l.id, title: l.title, content: l.content, type: l.type, year: l.year, confidence: l.confidence, people: l.people })),
  ...people.flatMap((p) =>
    p.funFacts.map((content, i) => ({ key: `ff-${p.id}-${i}`, content, type: "ciekawostka", confidence: "confirmed", people: [p.id] })),
  ),
];
out("insert into public.lore (id, title, content, lore_type, year, confidence, source_type, status) values");
out(
  loreRows
    .map(
      (l) =>
        `  (${id("lore", l.key)}, ${q(l.title)}, ${q(l.content)}, ${q(l.type)}, ${n(l.year)}, ${q(l.confidence)}, 'personal', ${DRAFT_LORE.has(l.key) ? "'draft'" : "'published'"})`,
    )
    .join(",\n") + "\non conflict (id) do nothing;",
);
out();

out("insert into public.lore_people (lore_id, person_id) values");
out(
  loreRows
    .flatMap((l) => l.people.map((p) => `  (${id("lore", l.key)}, ${id("person", p)})`))
    .join(",\n") + "\non conflict do nothing;",
);
out();
out("commit;");

const target = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(target, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${target}: ${people.length} people, ${relationships.length} relationships, ${events.length} events, ${loreRows.length} lore entries.`);
